name: jsonrpc2
version: 3.0.0
author: Jim Washington <washington.jim@gmail.com>
description: JSON-RPC (v2.0) utility classes for web applications. Invoke
  methods on another machine using JSON.
homepage: https://github.com/jwashin/jsonrpc2-dart

dependencies:
  http: ^0.13.1
  rpc_dispatcher: any
  rpc_exceptions: any

environment:
  sdk: '>=2.12.0 <3.0.0'

dev_dependencies:
  build_runner: any
  build_test: any
  pedantic: ^1.11.0
  reflectable: ^3.0.0
  reflector_dispatcher: ^1.0.1
  stream_channel: any
  test: ^1.16.5
