name: jsonrpc2
version: 2.1.0
author: Jim Washington <washington.jim@gmail.com>
description: JSON-RPC (v2.0) utilities for web applications. It's like XML-RPC,
  for calling methods on a remote server, but using JSON.
homepage: https://github.com/jwashin/jsonrpc2-dart

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  logging: ^1.0.0

dev_dependencies:
  pedantic: ^1.11.0
  html: ^0.15.0
  # effective_dart: ^1.0.0
  test: ^1.16.5
