name: jsonrpc2
version: 2.0.0
author: Jim Washington <washington.jim@gmail.com>
description: JSON-RPC (v2.0) utilities for web applications. It's like XML-RPC, for calling methods on a remote server, but using JSON.
homepage: https://github.com/jwashin/jsonrpc2-dart

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
#  browser: ^0.10.0
  logging:  ^0.11.0
 # logging_handlers: any

dev_dependencies:
  build_runner: ^0.10.0
  build_test: ^0.10.2
  build_web_compilers: ^0.4.0
  http_server: any
#  start: any
  test: any
  #stream_channel: ^1.6.0
